name: Staging Build
on:
  push:
    branches:
      - testdeploy
      - release
env:
  REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
  REACT_APP_MQTT_HOST: ${{secrets.REACT_APP_MQTT_HOST}}
  REACT_APP_MQTT_PORT: ${{secrets.REACT_APP_MQTT_PORT}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env file
        run: |
          echo REACT_APP_BASE_URL=$REACT_APP_BASE_URL >> .env
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          envkey_REACT_APP_MQTT_HOST: ${{ secrets.REACT_APP_MQTT_HOST }}
          envkey_REACT_APP_MQTT_PORT: ${{ secrets.REACT_APP_MQTT_PORT }}
          directory: './'
          file_name: '.env'
      - name: Make envfile prod
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          envkey_REACT_APP_MQTT_HOST: ${{ secrets.REACT_APP_MQTT_HOST }}
          envkey_REACT_APP_MQTT_PORT: ${{ secrets.REACT_APP_MQTT_PORT }}
          directory: './'
          file_name: '.env.production'
      - name: clean npm cache
        run: |
          npm cache clean --force
      - name: Npm Install
        run: |
          npm install
      - name: Staging Build
        run: |
          npm run build
        env:
          CI: false
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DEV_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"